import { Poppins , Montserrat } from "next/font/google";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";


const poppins = Poppins({
  subsets : ["latin"],
  weight : ["400", "700", "500"],
});

const myFont = Montserrat({
  subsets : ["latin"],
  weight : ["400", "700", "500"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}>
          <Header></Header>
          {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
